// name in json needs to match name of elementId for clarity

export const settingsDefaults = {form:{"raw-files-group": "folder",
									"raw-files-path": "undefined",
									"label-file-path": "undefined",
									"pickup-file-path": "undefined",
									"cell-files-path": "undefined",
									"output-path": "undefined",
									"extra-rows": ['Carrier', 'Reference'],
									"well-to-tmt-mapping": "default",
									"tmt-mapping-path": "undefined",
									"cell-population-names": "undefined",
									"meta-to-include": "undefined",
									"column-mismatches": "undefined",
									"label-missing-data": "Control",
									"row-regex": "R([^_]*)_",
									"col-regex": "C([^_]*)_",
									"pickup-type": "single",
									"offset": "18",
									"tech-type": "tmt"
									},
								private:{"raw-files-path-tag": "No raw files loaded",
									"label-file-path-tag": "No labels file loaded",
									"pickup-file-path-tag": "No pickup file loaded",
									"cell-files-path-tag": "No cell files loaded",
									"output-path-tag": "No output folder has been selected",
									"NextImportButton-text": "Complete all imports",
									"NextImportButton-disabled": true,
									"select-tmt-mapping-disabled": true,
									"tmt-mapping-path-tag": "No mapping CSV loaded",
									"name-job": "undefined",
									"row-valid": "valid",
									"col-valid": "valid",
									"offset-disabled": true}};

